name: build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  aqua: 
    name: Trivy
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner:limited
        with:
          args: trivy fs --scanners vuln,config,secret --sast .
    
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY_PROD }} #119
          AQUA_SECRET: ${{ secrets.AQUA_SECRET_PROD }} #119
          # AQUA_KEY: ${{ secrets.AQUA_KEY }} #119
          # AQUA_SECRET: ${{ secrets.AQUA_SECRET }} #119
          GITHUB_TOKEN: ${{ github.token }}
          # AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
          # CSPM_URL: https://stage.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: 'aqua'
        
